export const GET_BOOK_DETAIL_ID = 'GET_BOOK_DETAIL_ID';
export const GET_LIST_BOOK_DISCOUNT = 'GET_LIST_BOOK_DISCOUNT';
export const GET_LIST_BOOK_RECOMMEND = 'GET_LIST_BOOK_RECOMMEND';
export const GET_LIST_BOOK_POPULAR = 'GET_LIST_BOOK_POPULAR';